# 04 Pandas Cleaning

**Phase:** Phase1_Python_Pandas  
**Status:** 🔴 Not Started  
**Date Started:**  

---

In [20]:
import pandas as pd
import numpy as np

In [28]:
df = pd.DataFrame({
    'name' : ['bunty' ,'chunty'],
    'email' : ['for@go', 'hah@sad'],
    'gender' : ['M', 'F'],
    'age' : [1,256],
    'date' : [5,9]
})

df.duplicated().sum()     # count duplicates
df.drop_duplicates()      # remove them
df.drop_duplicates(subset=['name', 'email'])  # based on specific columns

     name    email gender  age  date
0   bunty   for@go      M    1     5
1  chunty  hah@sad      F  256     9

In [30]:
# fixing types 
df.dtypes                        # check types
df['age'] = df['age'].astype(int)        # convert to int
df['date'] = pd.to_datetime(df['date'])  # convert to datetime



# note 
# This will crash if any value is '25 years' or '' or NaN
df['age'] = df['age'].astype(int)

# Safer approach for real world data
df['age'] = pd.to_numeric(df['age'], errors='coerce')
# errors='coerce' → converts bad values to NaN instead of crashing

In [44]:
# string cleaning
df['name'].str.lower()           # lowercase
df['name'].str.strip()           # remove whitespace
df['name'].str.replace('_', ' ') # replace characters
df['name'].str.contains('Alice') # filter by string

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [25]:
# replacing wrong values 
df['gender'] = df['gender'].replace({'M': 'Male', 'F': 'Female'})
df['age'].replace(-1, np.nan)  # replace impossible values with NaN

0    1
1    2
Name: age, dtype: int64

In [26]:
# renaming columns 

df.rename(columns={'name': 'N', 'gender': 'g'}, inplace=True)
df.columns = df.columns.str.lower().str.strip()  # clean all at once

In [29]:
df['age'].clip(lower=0, upper=30)  # cap values between 0 and 300

0     1
1    30
Name: age, dtype: int64

In [45]:
df = pd.DataFrame({
    'name': ['  Alice', 'BOB  ', '  charlie  ', 'DAVID'],
    'city': ['new york', 'NEW YORK', 'New York', 'new york']
})

In [46]:
df['name'] = df['name'].str.strip().str.title()
df['city'] = df['city'].str.lower()

In [47]:
df

      name      city
0    Alice  new york
1      Bob  new york
2  Charlie  new york
3    David  new york

In [50]:

df = pd.DataFrame({
    'id':     [1, 2, 3, 2, 4],
    'gender': ['M', 'F', 'male', 'F', 'FEMALE'],
    'age':    [25, 30, -1, 30, 28]
})

In [51]:
df

   id  gender  age
0   1       M   25
1   2       F   30
2   3    male   -1
3   2       F   30
4   4  FEMALE   28

In [64]:
# Standardize the gender column so all values are either 'Male' or 'Female'
df['gender'] = df['gender'].str.lower().replace({
    'm': 'Male', 
    'f': 'Female',
    'male': 'Male',
    'female': 'Female'
})
# Replace -1 in age with NaN
df['age'] = df['age'].replace(-1, np.nan)

# Remove duplicate rows based on the id column
df = df.drop_duplicates(subset='id')

In [63]:
# optimised 

df['gender'] = df['gender'].str.lower().str[0].replace({
    'm': 'Male', 
    'f': 'Female'
})
# str[0] grabs first letter → 'm' or 'f' always → clean mapping

In [65]:
df = pd.DataFrame({
    'age':    [25, 30, 150, -5, 28],
    'salary': [50000, 60000, 10000000, 45000, 55000]
})

In [69]:
# Clip age between 0 and 100
df['age'] = df['age'].clip(lower=0, upper=100)
# Clip salary between 20000 and 200000
df['salary'] = df['salary'].clip(lower=20000, upper=200000)
df

   age  salary
0   25   50000
1   30   60000
2  100  200000
3    0   45000
4   28   55000