# 05 Pandas Grouping

**Phase:** Phase1_Python_Pandas  
**Status:** Done    
**Date Started:**  

---

#### groupby()
- groups the data based on columns and allow us to perform operation on it 
- like : data.groupby('Class')['Score'].mean()


#### agg()
- allow us to perform more that one aggregation operation in a single time 
- like : data.groupby('Class')['Score].agg(['mean', 'max', 'min', 'count])
- second : data.grouby('Class').agg({ 'Score' : ['mean', 'max'], 'Age' : ['mean', 'max]})

#### pivot_table()
- its like a increament of gropby() with ability of grouping in 2 dimensions
- like - pd.pivot_table(df, 
values = 'Survived'
index = 'Pclass'
columns = 'gender'
aggfunc = 'mean'
)

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'../datasets/data_files/Titanic-Dataset.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
# Question 1 > 
# Write code to find the average age and total fare paid for each passenger class (Pclass) — both in a single operation.

In [11]:
data.groupby('Pclass').agg({
    'Age' : 'mean',
    'Fare' : 'sum'
})

              Age        Fare
Pclass
1       38.233441  18177.4125
2       29.877630   3801.8417
3       25.140620   6714.6951

In [12]:
# Question 2
# Using the same Titanic dataset — write a pivot table that shows the survival rate for each combination of Pclass and Sex. 🎯

In [15]:
pd.pivot_table(data,
               values='Survived',
               index='Pclass', 
               columns='Sex',
               aggfunc='mean')

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [16]:
# One query — three things:
# Using Titanic, write code to find for each Pclass:

# Average age
# Survival rate
# Total number of passengers

# All in a single agg() call. 🎯

In [19]:
data.groupby('Pclass').agg({
    'Age' : 'mean',
    'Survived' : 'mean',
    'PassengerId' : 'count'
})

              Age  Survived  PassengerId
Pclass
1       38.233441  0.629630          216
2       29.877630  0.472826          184
3       25.140620  0.242363          491

In [20]:
# improvement 

data.groupby('Pclass').agg(
    avg_age        = ('Age', 'mean'),
    survival_rate  = ('Survived', 'mean'),
    total_passengers = ('PassengerId', 'count')
)

          avg_age  survival_rate  total_passengers
Pclass
1       38.233441       0.629630               216
2       29.877630       0.472826               184
3       25.140620       0.242363               491

In [28]:
df = pd.DataFrame({
    'city':     ['Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi'],
    'category': ['A', 'B', 'A', 'A', 'B'],
    'sales':    [100, 200, 150, 300, 120],
    'profit':   [10, 40, 30, 60, 20]
})
df

     city category  sales  profit
0   Delhi        A    100      10
1  Mumbai        B    200      40
2   Delhi        A    150      30
3  Mumbai        A    300      60
4   Delhi        B    120      20

In [29]:
# Write a pivot table showing total sales for each city (rows) and category (columns).
# And tell me — what happens to missing combinations if a city has no sales in a certain category? 🎯

In [31]:
pd.pivot_table(df,
               values='sales',
               index='city',
               columns='category',
               aggfunc='sum'
               )

# misssing combination may be filled with 0, but nooooo

category    A    B
city
Delhi     250  120
Mumbai    300  200

In [32]:
# correction 
# missing values are filled with NaN

# to handle it 

pd.pivot_table(df, values='sales', index='city',
               columns='category', aggfunc='sum',
               fill_value=0)  # ← fills NaN with 0

category    A    B
city
Delhi     250  120
Mumbai    300  200

In [34]:
df = pd.DataFrame({
    'department': ['HR', 'Tech', 'HR', 'Tech', 'HR', 'Tech'],
    'gender':     ['M', 'M', 'F', 'F', 'M', 'F'],
    'salary':     [50000, 90000, 45000, 95000, 52000, 88000],
    'experience': [2, 5, 3, 7, 4, 6]
})
df

  department gender  salary  experience
0         HR      M   50000           2
1       Tech      M   90000           5
2         HR      F   45000           3
3       Tech      F   95000           7
4         HR      M   52000           4
5       Tech      F   88000           6

In [35]:
# Write a single query to find for each department:

# Average salary for Male and Female separately
# Maximum experience

In [45]:
df.groupby(['department', 'gender']).agg(
    Average_Salary=('salary', 'mean'),
    Max_Experience=('experience', 'max')
)

                   Average_Salary  Max_Experience
department gender
HR         F              45000.0               3
           M              51000.0               4
Tech       F              91500.0               7
           M              90000.0               5

In [47]:

# important 
# fill_value = 0 to handle any missing combination 

# pd.pivot_table(df, values='sales', index='city',
#                columns='category', aggfunc='sum',
#                fill_value=0)  # ← fills NaN with 0